-- ============================================================
-- lets-go — Initial Schema
-- ============================================================

-- --------------------------------------------------------
-- Helper: auto-update updated_at
-- --------------------------------------------------------
create or replace function public.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;


-- --------------------------------------------------------
-- exchange_rates: daily BCV USD→Bs. rate
-- --------------------------------------------------------
create table public.exchange_rates (
  id         bigint generated by default as identity primary key,
  rate_date  date          not null unique,
  rate_bsf   numeric(12,4) not null check (rate_bsf > 0),
  created_at timestamptz   not null default now()
);

alter table public.exchange_rates enable row level security;

create policy "Public read exchange_rates"
  on public.exchange_rates
  for select
  using (true);


-- --------------------------------------------------------
-- operators: external businesses that register parking lots
-- --------------------------------------------------------
create table public.operators (
  id         uuid        primary key default gen_random_uuid(),
  name       text        not null,
  rif        text        unique,
  email      text,
  phone      text,
  is_active  boolean     not null default true,
  created_at timestamptz not null default now()
);

alter table public.operators enable row level security;

create policy "Authenticated can read operators"
  on public.operators
  for select
  to authenticated
  using (true);


-- --------------------------------------------------------
-- profiles: app users (phone + cedula auth)
-- --------------------------------------------------------
create table public.profiles (
  id           uuid          primary key default gen_random_uuid(),
  auth_user_id uuid          references auth.users (id) on delete set null,
  full_name    text          not null,
  phone        text          not null unique,
  cedula       text          not null unique,
  balance_usd  numeric(10,4) not null default 0 check (balance_usd >= 0),
  created_at   timestamptz   not null default now(),
  updated_at   timestamptz   not null default now()
);

alter table public.profiles enable row level security;

create policy "Users can read own profile"
  on public.profiles
  for select
  to authenticated
  using ((select auth.uid()) = auth_user_id);

create policy "Users can update own profile"
  on public.profiles
  for update
  to authenticated
  using ((select auth.uid()) = auth_user_id)
  with check ((select auth.uid()) = auth_user_id);

create index profiles_phone_idx  on public.profiles (phone);
create index profiles_cedula_idx on public.profiles (cedula);

create trigger profiles_set_updated_at
  before update on public.profiles
  for each row execute function public.set_updated_at();


-- --------------------------------------------------------
-- parking_lots: marketplace listings
-- --------------------------------------------------------
create table public.parking_lots (
  id                 uuid             primary key default gen_random_uuid(),
  operator_id        uuid             not null references public.operators (id) on delete restrict,
  name               text             not null,
  address            text             not null,
  city               text             not null,
  latitude           double precision not null,
  longitude          double precision not null,
  total_spots        integer          not null check (total_spots > 0),
  available_spots    integer          not null check (available_spots >= 0),
  price_per_hour_usd numeric(8,4)     not null check (price_per_hour_usd >= 0),
  open_hours         text,
  is_open            boolean          not null default true,
  rating             numeric(2,1)     check (rating between 0 and 5),
  features           text[]           not null default '{}',
  created_at         timestamptz      not null default now(),
  updated_at         timestamptz      not null default now(),
  constraint chk_available_lte_total check (available_spots <= total_spots)
);

alter table public.parking_lots enable row level security;

create policy "Public can read parking lots"
  on public.parking_lots
  for select
  using (true);

create index parking_lots_location_idx on public.parking_lots (city, is_open);

create trigger parking_lots_set_updated_at
  before update on public.parking_lots
  for each row execute function public.set_updated_at();


-- --------------------------------------------------------
-- vehicles: user's registered vehicles
-- --------------------------------------------------------
create table public.vehicles (
  id         uuid        primary key default gen_random_uuid(),
  profile_id uuid        not null references public.profiles (id) on delete cascade,
  plate      text        not null,
  brand      text        not null,
  model      text        not null,
  color      text        not null,
  is_default boolean     not null default false,
  created_at timestamptz not null default now(),
  unique (profile_id, plate)
);

alter table public.vehicles enable row level security;

create policy "Users can read own vehicles"
  on public.vehicles
  for select
  to authenticated
  using ((select auth.uid()) = (select auth_user_id from public.profiles where id = profile_id));

create policy "Users can insert own vehicles"
  on public.vehicles
  for insert
  to authenticated
  with check ((select auth.uid()) = (select auth_user_id from public.profiles where id = profile_id));

create policy "Users can update own vehicles"
  on public.vehicles
  for update
  to authenticated
  using ((select auth.uid()) = (select auth_user_id from public.profiles where id = profile_id))
  with check ((select auth.uid()) = (select auth_user_id from public.profiles where id = profile_id));

create policy "Users can delete own vehicles"
  on public.vehicles
  for delete
  to authenticated
  using ((select auth.uid()) = (select auth_user_id from public.profiles where id = profile_id));

create index vehicles_profile_idx on public.vehicles (profile_id);


-- --------------------------------------------------------
-- parking_sessions: active and historical parking events
-- --------------------------------------------------------
create table public.parking_sessions (
  id                 uuid          primary key default gen_random_uuid(),
  profile_id         uuid          not null references public.profiles (id) on delete restrict,
  parking_lot_id     uuid          not null references public.parking_lots (id) on delete restrict,
  vehicle_id         uuid          not null references public.vehicles (id) on delete restrict,
  started_at         timestamptz   not null default now(),
  ended_at           timestamptz,
  price_per_hour_usd numeric(8,4)  not null,
  total_cost_usd     numeric(10,4),
  exchange_rate_bsf  numeric(12,4),
  status             text          not null default 'active'
                       check (status in ('active', 'completed', 'cancelled')),
  constraint chk_session_end_after_start check (ended_at is null or ended_at > started_at),
  constraint chk_session_cost_when_closed check (
    status = 'active' or total_cost_usd is not null
  )
);

alter table public.parking_sessions enable row level security;

create policy "Users can read own sessions"
  on public.parking_sessions
  for select
  to authenticated
  using ((select auth.uid()) = (select auth_user_id from public.profiles where id = profile_id));

create policy "Users can insert own sessions"
  on public.parking_sessions
  for insert
  to authenticated
  with check ((select auth.uid()) = (select auth_user_id from public.profiles where id = profile_id));

create policy "Users can update own sessions"
  on public.parking_sessions
  for update
  to authenticated
  using ((select auth.uid()) = (select auth_user_id from public.profiles where id = profile_id))
  with check ((select auth.uid()) = (select auth_user_id from public.profiles where id = profile_id));

create index parking_sessions_profile_idx on public.parking_sessions (profile_id);
create index parking_sessions_lot_idx     on public.parking_sessions (parking_lot_id);
create index parking_sessions_status_idx  on public.parking_sessions (status) where status = 'active';


-- --------------------------------------------------------
-- transactions: wallet movement ledger
-- --------------------------------------------------------
create table public.transactions (
  id                 uuid          primary key default gen_random_uuid(),
  profile_id         uuid          not null references public.profiles (id) on delete restrict,
  parking_session_id uuid          references public.parking_sessions (id) on delete set null,
  type               text          not null check (type in ('recharge', 'parking', 'refund')),
  amount_usd         numeric(10,4) not null check (amount_usd > 0),
  is_credit          boolean       not null,
  exchange_rate_bsf  numeric(12,4) not null check (exchange_rate_bsf > 0),
  description        text          not null,
  payment_method     text,
  status             text          not null default 'completed'
                       check (status in ('completed', 'pending', 'failed')),
  created_at         timestamptz   not null default now(),
  constraint chk_tx_parking_has_session check (
    type != 'parking' or parking_session_id is not null
  )
);

alter table public.transactions enable row level security;

create policy "Users can read own transactions"
  on public.transactions
  for select
  to authenticated
  using ((select auth.uid()) = (select auth_user_id from public.profiles where id = profile_id));

create policy "Users can insert own transactions"
  on public.transactions
  for insert
  to authenticated
  with check ((select auth.uid()) = (select auth_user_id from public.profiles where id = profile_id));

create index transactions_profile_idx on public.transactions (profile_id, created_at desc);
create index transactions_session_idx on public.transactions (parking_session_id) where parking_session_id is not null;
